In [1]:
import duckdb
import os
import sys
import pandas as pd
from datetime import datetime

In [2]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [13]:
arquivo = 'z0019_2.csv' ## nome do arquivo a ser lido
data_ingestao = datetime.now() ## pega a data e hora atual
df = pd.read_csv(f'../landing/{arquivo}', sep=';') ## lê o arquivo csv
df['nome_arquivo'] = arquivo ## adiciona o nome do arquivo
df['data_ingestao'] = data_ingestao ## adiciona a data de ingestão
df.head() ## mostra as 5 primeiras linhas do dataframe

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-02-09 22:00:11.558456
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-02-09 22:00:11.558456
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-02-09 22:00:11.558456

In [14]:
con.execute("""CREATE TABLE IF NOT EXISTS bronze_produtos(
    NATBR VARCHAR(255),
    MAKTX_produto VARCHAR(255),
    WERKS VARCHAR(255),
    AINS DECIMAL(10,2),
    LABST VARCHAR(255),
    nome_arquivo VARCHAR(255),
    data_ingestao TIMESTAMP
    )
""")## cria uma tabela bronze_produtos no banco de dados DuckDB com os dados do dataframe df

In [16]:
con.execute("""INSERT INTO bronze_produtos SELECT * FROM df""") ## insere os dados do dataframe df na tabela bronze_produtos

In [20]:
resultado = con.execute("""SELECT * FROM bronze_z0019""").fetchdf() ## seleciona todos os dados da tabela bronze_produtos e armazena em um dataframe resultado
resultado.head(6) ## mostra as 5 primeiras linhas do dataframe resultado

,NATBR,MAKTX_produto,WERKS,AINS,LABST,nome_arquivo,data_ingestao
0,10001,PARAFUSO,BT10,100.0,100,z0019_1.csv,2026-02-09 21:54:46.894980
1,10002,MARTELO,BT50,100.0,1500,z0019_1.csv,2026-02-09 21:54:46.894980
2,10003,PREGO,BT10,100.0,50,z0019_1.csv,2026-02-09 21:54:46.894980
3,10004,SERRA,BT50,100.0,200,z0019_2.csv,2026-02-09 22:00:11.558456
4,10005,MACHADO,BT50,100.0,100,z0019_2.csv,2026-02-09 22:00:11.558456
5,10003,PREGO,BT10,100.0,60,z0019_2.csv,2026-02-09 22:00:11.558456

In [19]:
con.execute(""" ALTER TABLE bronze_produtos RENAME TO bronze_z0019""") ## renomeia a tabela bronze_produtos para bronze_z0019

In [21]:
con.close